# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |django_config|
  # Every Vagrant virtual environment requires a box to build off of.
  django_config.vm.box = "bionic64"
  django_config.vm.provision "shell", inline: <<-SHELL
  
django_config.vm.box_url = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-vagrant.box"
  

django_config.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", 2048]
    p.customize ["modifyvm", :id, "--cpus", 2]
    p.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
  end

  # Copy file
django_config.vm.provision "file", source: "emptyfile", destination: "~/emptyfile"
end

# python and pip
echo 'Install packages'
apt install -y python3 psycopg2
curl -s https://bootstrap.pypa.io/get-pip.py | python3.4 
pip3 install django


SHELL
end
